---
name: general_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  flutter_local_notifications: ^17.2.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  oktoast: ^3.4.0
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  rename: ^3.0.2
  shimmer: ^3.0.0
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.0
  vibration: ^2.0.0
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/launcher/
    - assets/icons/
    - assets/anim/
