---
name: general_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  chat_bubbles: ^1.7.0
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.21.2
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.3.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.2.0
  get: ^4.7.2
  get_storage: ^2.1.1
  grouped_list: ^6.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.6.1
  lottie: ^3.3.1
  oktoast: ^3.4.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  rename: ^3.1.0
  shimmer: ^3.0.0
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.2
  vibration: ^3.1.3
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/launcher/
    - assets/icons/
    - assets/anim/
