// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjg-_ywkwvSecCsYUSuYIi6WB8tcSRESs',
    appId: '1:523032872722:web:abbb6b6c71628e208f95cb',
    messagingSenderId: '523032872722',
    projectId: 'freelancing-project-7ed76',
    authDomain: 'freelancing-project-7ed76.firebaseapp.com',
    storageBucket: 'freelancing-project-7ed76.appspot.com',
    measurementId: 'G-49Q9W4J8F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsnJALJrWq3omUMtgvZyKWk4vCDOXQWrA',
    appId: '1:523032872722:android:46e91a161a46f27b8f95cb',
    messagingSenderId: '523032872722',
    projectId: 'freelancing-project-7ed76',
    storageBucket: 'freelancing-project-7ed76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLBq8iFeEDjI1Bc9AbQV5o6ahJyJgRMek',
    appId: '1:523032872722:ios:2c054833878bf7578f95cb',
    messagingSenderId: '523032872722',
    projectId: 'freelancing-project-7ed76',
    storageBucket: 'freelancing-project-7ed76.appspot.com',
    iosBundleId: 'com.general.app.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLBq8iFeEDjI1Bc9AbQV5o6ahJyJgRMek',
    appId: '1:523032872722:ios:af072044771ee2da8f95cb',
    messagingSenderId: '523032872722',
    projectId: 'freelancing-project-7ed76',
    storageBucket: 'freelancing-project-7ed76.appspot.com',
    iosBundleId: 'com.example.appWidgetsExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjg-_ywkwvSecCsYUSuYIi6WB8tcSRESs',
    appId: '1:523032872722:web:a9a0ab40f5e1c1788f95cb',
    messagingSenderId: '523032872722',
    projectId: 'freelancing-project-7ed76',
    authDomain: 'freelancing-project-7ed76.firebaseapp.com',
    storageBucket: 'freelancing-project-7ed76.appspot.com',
    measurementId: 'G-9BJNLG24H1',
  );
}